"""Independently reconstruct every eligibility input from an original demo.

The full decoder starts at the original beginning, preserving missing-baseline
failures. Commands, states, rounds and events are compared in source order;
phase and pause/shot context are regenerated by separately pinned tools. No
published JSON proof is accepted as a substitute for this reconstruction.

A process-local cache avoids decoding a match for every clip. Every cache lookup
rehashes all original, canonical, sidecar, executable and implementation bytes.
It never upgrades recording-build support, button semantics or image evidence.
"""
from __future__ import annotations

from copy import deepcopy
from collections import OrderedDict
from itertools import zip_longest
from pathlib import Path
import subprocess
import threading

import pyarrow as pa
import pyarrow.dataset as ds
import pyarrow.parquet as pq

from . import command_reverification as commands
from .control_label_audit import canonical_row_sha256
from .io import parsed_manifest, read_json, sha256_file, write_json

PROFILE = "cs2-original-full-competitive-source-reconstruction-v1"
PROJECT = Path(__file__).resolve().parents[2]
TABLES = ("usercmd.parquet", "player_state.parquet", "rounds.parquet", "events.parquet")
TOOL_PINS = {
    "bin/cs2-phases.exe": "8c5e39c58278c99d01ee9749a77ecb75c102b859713ccc48a6e1ce956ea6c521",
    "bin/cs2-context.exe": "908db55df683629a1101a645475c9732c3e59db6ee014f2b157ce10b686e82ba",
    "tools/usercmd-extractor/cmd/cs2-phases/main.go": "e3eec9962633ab6959d3b34fe9dfd4fbe45303e1e24bf4549e54deef3415c8b7",
    "tools/usercmd-extractor/cmd/cs2-context/main.go": "b1de484109a6a8bdc46140dd346c3e96032cc615fdd7a64dd37409f889a68c41",
}
MANIFEST_EXCLUSIONS = ("ingested_at", "source_path", "files")
MAX_COMPLETED_SOURCES = 4
_COMPLETED = OrderedDict()
_LOCK = threading.RLock()


def _require(condition, message):
    if not condition:
        raise ValueError(message)


def _tool_files():
    watched = commands._decoder_files()
    for name, digest in TOOL_PINS.items():
        path = (PROJECT/name).resolve()
        _require(path.is_file() and sha256_file(path) == digest,
            "Inspected competitive source tool or Go source bytes changed: " + name)
        watched[str(path)] = digest
    # These are implementation provenance, not caller-supplied trust flags.
    for name in ("competitive_source_verification.py", "command_reverification.py", "io.py", "control_label_audit.py"):
        path = Path(__file__).with_name(name).resolve()
        watched[str(path)] = sha256_file(path)
    return watched


def _unchanged(watched):
    _require(all(Path(path).is_file() and sha256_file(Path(path)) == digest for path, digest in watched.items()),
        "Competitive reconstruction source or tool changed during verification")


def _manifest_body(manifest, source):
    _require(manifest.get("parse_status") == "complete" and manifest.get("partial") is False,
        "Full competitive source reconstruction requires a complete nonpartial parse")
    _require(manifest.get("tick_rate") == 64 and isinstance(manifest.get("match_id"), str)
        and bool(manifest["match_id"]), "Competitive source needs 64 Hz and an explicit match ID")
    for key, expected in commands.DECODER_FIELDS.items():
        _require(str(manifest.get(key)) == expected, "Unsupported full-source decoder profile")
    _require(manifest.get("sha256") == manifest.get("demo_id") and manifest.get("file_size") == source.stat().st_size
        and manifest.get("file_name") == source.name, "Source manifest identity, filename or size differs")
    # A source may have been moved after extraction. Its current original bytes
    # are hashed independently; the old source_path is descriptive only.
    return {key: value for key, value in manifest.items() if key not in MANIFEST_EXCLUSIONS}


def _array_equal(left, right):
    """Arrow equality plus bitwise floats, including nested fields and -0.0."""
    if left.type != right.type or not left.equals(right):
        return False
    kind = left.type
    if pa.types.is_floating(kind):
        integer = pa.int32() if kind.bit_width == 32 else pa.int64()
        return left.view(integer).equals(right.view(integer))
    if pa.types.is_struct(kind):
        return all(_array_equal(left.field(i), right.field(i)) for i in range(kind.num_fields))
    if pa.types.is_list(kind) or pa.types.is_large_list(kind):
        return _array_equal(left.flatten(), right.flatten())
    return True


def compare_tables(original, reconstructed, *, require_sequential_commands=False):
    """Bounded-memory, exact typed table comparison in decoder source order."""
    original, reconstructed = Path(original), Path(reconstructed)
    with pq.ParquetFile(original) as before, pq.ParquetFile(reconstructed) as fresh:
        return _compare_open_tables(original, reconstructed, before, fresh, require_sequential_commands)


def _compare_open_tables(original, reconstructed, before, fresh, require_sequential_commands):
    _require(before.schema_arrow.equals(fresh.schema_arrow, check_metadata=False),
        "Original and reconstructed table schemas differ: " + original.name)
    _require(before.metadata.num_rows == fresh.metadata.num_rows,
        "Original and reconstructed table row counts differ: " + original.name)
    count = before.metadata.num_rows
    _require(not require_sequential_commands or count > 0, "No reconstructed command rows")
    # Equal freshly decoded file bytes prove every typed value and its order.
    byte_identical = sha256_file(original) == sha256_file(reconstructed)
    if not byte_identical:
        offset = 0
        for a, b in zip_longest(before.iter_batches(batch_size=8192), fresh.iter_batches(batch_size=8192)):
            _require(a is not None and b is not None and a.num_rows == b.num_rows,
                "Reconstructed table batch coverage differs: " + original.name)
            _require(all(_array_equal(x, y) for x, y in zip(a.columns, b.columns)),
                "Canonical table differs from original-demo reconstruction: " + original.name + " at batch row " + str(offset))
            offset += a.num_rows
        _require(offset == count, "Table comparison ended before its declared row count")
    if require_sequential_commands:
        expected = 0
        for batch in fresh.iter_batches(batch_size=65536, columns=["command_row_id"]):
            ids = batch.column(0)
            _require(pa.types.is_int64(ids.type) and ids.null_count == 0
                and ids.equals(pa.array(range(expected, expected + len(ids)), type=pa.int64())),
                "Reconstructed command row IDs are not complete and sequential")
            expected += len(ids)
    return {"row_count": count, "comparison": "byte_identical" if byte_identical else "all_typed_values_bitwise_floats_and_source_order",
        "canonical_sha256": sha256_file(original), "reconstructed_sha256": sha256_file(reconstructed),
        "ignored_columns": [], "ignored_parquet_metadata": not byte_identical}


def _sidecar_body(value, canonical, kind, *, original=False):
    expected = {"phase": (1, "cs2-phases-v1"), "context": (2, "cs2-context-v2")}[kind]
    producer = value.get("producer")
    historical_phase = original and kind == "phase" and "producer" not in value
    _require(value.get("schema_version") == expected[0] and (producer == expected[1] or historical_phase),
        "Unsupported reconstructed " + kind + " schema")
    _require(value.get("demo_id") == canonical["demo_id"] and value.get("source_demo_sha256") == canonical["demo_id"]
        and value.get("parse_status") == "complete" and value.get("partial") is False
        and value.get("timing_clock") == "demo_tick" and value.get("parser_version") == commands.DECODER_FIELDS["parser_version"],
        "Reconstructed " + kind + " source or completeness differs")
    if kind == "phase":
        events = value.get("events", [])
        _require(bool(events) and events[-1].get("kind") == "demo_end", "Phase reconstruction lacks its complete source ending")
    else:
        _require(value.get("evidence_loss_warnings") == 0 and value.get("warning_policy") == "rule-and-shot-evidence-v1",
            "Context reconstruction contains evidence-loss warnings")
    # The original phase-v1 artifact predates its descriptive producer field.
    # The fresh tool must always emit the exact pinned producer. A present but
    # different original producer rejects, and no event field is excluded.
    excluded = {"source_demo_path", "producer"} if kind == "phase" else {"source_demo_path"}
    return {key: item for key, item in value.items() if key not in excluded}


def compare_sidecars(original, reconstructed, canonical, kind):
    a, b = _sidecar_body(read_json(original), canonical, kind, original=True), _sidecar_body(read_json(reconstructed), canonical, kind)
    digest = canonical_row_sha256(b)
    _require(canonical_row_sha256(a) == digest,
        "Canonical " + kind + " eligibility differs from fresh original-demo reconstruction")
    return {"comparison": "all_typed_fields_and_source_event_order", "semantic_sha256": digest,
        "ignored_fields": ["source_demo_path"],
        "phase_producer_policy": "fresh_cs2-phases-v1_required; original_absence_allowed; differing_present_producer_rejected" if kind == "phase" else None,
        "canonical_sha256": sha256_file(original),
        "reconstructed_sha256": sha256_file(reconstructed)}


def _run_sidecar(kind, source, output):
    executable = PROJECT/("bin/cs2-phases.exe" if kind == "phase" else "bin/cs2-context.exe")
    result = subprocess.run([str(executable), "--input", str(source), "--out", str(output)],
        cwd=PROJECT, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=3600,
        creationflags=getattr(subprocess, "CREATE_NO_WINDOW", 0), check=False)
    _require(result.returncode == 0 and output.is_file(), "Fresh " + kind + " source decoder failed")


def _reconstruct(source, parsed, canonical, phase_path, state_context):
    with commands._temporary_prefix() as temporary:
        invocation = commands._extract(source, canonical["match_id"], 0, temporary)
        fresh = temporary/canonical["demo_id"]
        _require((fresh/"manifest.json").is_file(), "Fresh full extractor did not publish source tables")
        manifest = parsed_manifest(fresh, TABLES)
        _require(canonical_row_sha256(_manifest_body(canonical, source)) == canonical_row_sha256(_manifest_body(manifest, source)),
            "Canonical full-source manifest metadata/counts/warnings differ from reconstruction")
        compared = {name: compare_tables(parsed/name, fresh/name, require_sequential_commands=name == "usercmd.parquet") for name in TABLES}
        for name, field in (("usercmd.parquet", "command_count"), ("player_state.parquet", "state_count"), ("rounds.parquet", "round_count")):
            _require(compared[name]["row_count"] == canonical.get(field), "Source manifest count disagrees with table: " + name)
        for kind in ("phase", "context"):
            _run_sidecar(kind, source, temporary/(kind + ".json"))
        phase = compare_sidecars(phase_path, temporary/"phase.json", canonical, "phase")
        context = compare_sidecars(state_context, temporary/"context.json", canonical, "context")
        return {"tables": compared, "phase": phase, "context": context,
            "canonical_manifest_sha256": sha256_file(parsed/"manifest.json"),
            "reconstructed_manifest_semantic_sha256": canonical_row_sha256(_manifest_body(manifest, source)),
            "ignored_manifest_fields": list(MANIFEST_EXCLUSIONS), "extractor_invocation": invocation,
            "fresh_warning_counts": manifest.get("warnings", {}),
            "fresh_payload_counts": {name: manifest.get(name) for name in
                ("full_payload_count", "delta_payload_count", "eligible_payload_count", "ineligible_payload_count")}}


def _selected_digests(parsed, rows):
    """Bind untouched requested rows without retaining millions of Python rows."""
    if rows is None:
        return {}
    rows = list(rows)
    ids = [row.get("command_row_id") for row in rows]
    _require(all(type(value) is int and value >= 0 for value in ids) and len(set(ids)) == len(ids),
        "Requested command row IDs must be unique nonnegative integers")
    if not ids:
        return {}
    actual = ds.dataset(parsed/"usercmd.parquet").to_table(filter=ds.field("command_row_id").isin(ids)).to_pylist()
    digests = {row["command_row_id"]: canonical_row_sha256(row) for row in actual}
    _require(len(actual) == len(digests) == len(ids) and set(digests) == set(ids), "Requested reconstructed commands are missing or ambiguous")
    _require(all(canonical_row_sha256(row) == digests[row["command_row_id"]] for row in rows),
        "Requested command row differs from the fully reconstructed canonical source")
    return digests


def reverify_competitive_source(source_demo: Path, parsed: Path, phase_path: Path, state_context: Path, *, command_rows=None):
    """Recompute full evidence, or reuse only an unchanged in-process reconstruction.

    ``command_rows`` are untouched original Parquet rows. Omitting them verifies
    the complete source but returns no selected row proofs. No caller can provide
    a cached proof or verification boolean. Build, image, HUD, button and causal
    support gates remain the responsibility of the composed acceptance verifier.
    """
    source, parsed = Path(source_demo).resolve(), Path(parsed).resolve()
    phase_path, state_context = Path(phase_path).resolve(), Path(state_context).resolve()
    with _LOCK:
        watched = _tool_files()
        canonical = parsed_manifest(parsed, TABLES)
        _manifest_body(canonical, source)
        _require(source.is_file() and sha256_file(source) == canonical["demo_id"], "Original demo bytes differ from the canonical source")
        for path in (source, parsed/"manifest.json", *(parsed/name for name in TABLES), phase_path, state_context):
            watched[str(path)] = sha256_file(path)
        # A hash changed since parsed_manifest read its bytes must reject rather
        # than becoming the new baseline for cache lookup.
        _require(all(watched[str(parsed/name)] == canonical["files"][name] for name in TABLES), "Canonical tables changed during source setup")
        _require(watched[str(source)] == canonical["demo_id"], "Original demo changed during source setup")
        _require(canonical_row_sha256(read_json(parsed/"manifest.json")) == canonical_row_sha256(canonical), "Canonical manifest changed during source setup")
        key = commands._digest(watched)
        compared = _COMPLETED.get(key)
        if compared is None:
            compared = _reconstruct(source, parsed, canonical, phase_path, state_context)
        digests = _selected_digests(parsed, command_rows)
        _unchanged(watched)
        if MAX_COMPLETED_SOURCES > 0:
            _COMPLETED[key] = deepcopy(compared)
            _COMPLETED.move_to_end(key)
            while len(_COMPLETED) > MAX_COMPLETED_SOURCES:
                _COMPLETED.popitem(last=False)
        provenance = {"profile": PROFILE, "source_demo_sha256": canonical["demo_id"], "match_id": canonical["match_id"],
            "scope": "full_original_demo_commands_states_rounds_events_phase_and_context",
            "decoder_profile": deepcopy(commands.DECODER_FIELDS), "comparison": deepcopy(compared),
            "source_files": watched, "selected_command_count": len(digests),
            "selected_row_digest_sha256": commands._digest(sorted(digests.items())),
            "cache_policy": "process_local_success_only; all_input_and_tool_bytes_rehashed_on_every_use",
            "baseline_failures_retained": True, "ignored_command_columns": []}
        proof_sha = commands._digest(provenance)
        return {"schema_version": 1, "profile": PROFILE, "status": "original_competitive_source_reconstructed_exactly",
            "provenance": provenance, "proof_sha256": proof_sha, "source_files": dict(watched), "command_row_digests": digests,
            "command_sources": {row_id: {"status": "verified", "reason_codes": [], "canonical_row_sha256": digest,
                "reconstruction_proof_sha256": proof_sha, "live_packet_envelope_association_required": True} for row_id, digest in digests.items()},
            "recorded_server_build_support_verified": False, "button_semantics_verified": False, "training_ready": False}


def main(argv=None):
    import argparse
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source-demo", type=Path, required=True)
    parser.add_argument("--parsed", type=Path, required=True)
    parser.add_argument("--phase", type=Path, required=True)
    parser.add_argument("--state-context", type=Path, required=True)
    parser.add_argument("--out", type=Path, required=True)
    args = parser.parse_args(argv)
    _require(not args.out.exists(), "Refusing to overwrite a source verification report")
    result = reverify_competitive_source(args.source_demo, args.parsed, args.phase, args.state_context)
    write_json(args.out, result)
    print(result["status"], result["proof_sha256"])
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
